import assert from "node:assert/strict";
import { NextRequest, NextResponse } from "next/server";
process.env.APP_SESSION_SECRET = "test-secret-which-is-more-than-thirty-two-characters";
import { cookieShouldBeSecure, createSession, hashPassword, readSession, setSessionCookie, verifyPassword } from "../lib/auth";
const password = "Long_Test_Password_2026!";
const hash = hashPassword(password);
assert.equal(verifyPassword(password, hash), true);
assert.equal(verifyPassword("incorrect", hash), false);
const token = createSession({ userId: "u1", email: "admin@example.test", role: "ADMIN" });
assert.equal(readSession(token)?.role, "ADMIN");
assert.equal(readSession(`${token}bad`), null);

const previousNodeEnv = process.env.NODE_ENV;
process.env.NODE_ENV = "production";
assert.equal(cookieShouldBeSecure({ protocol: "http:" }), false);
assert.equal(cookieShouldBeSecure({ protocol: "https:" }), true);
assert.equal(cookieShouldBeSecure({ forwardedProto: "http", protocol: "https:" }), false);
assert.equal(cookieShouldBeSecure({ forwardedProto: "https", protocol: "http:" }), true);
assert.equal(cookieShouldBeSecure({ forwardedProto: "https, http", protocol: "http:" }), true);
assert.equal(cookieShouldBeSecure({}), true);
process.env.NODE_ENV = "development";
assert.equal(cookieShouldBeSecure({}), false);
process.env.NODE_ENV = "production";
const httpLogin = new NextRequest("http://127.0.0.1:3000/api/auth/login", { method: "POST" });
const httpResponse = NextResponse.json({ success: true });
setSessionCookie(httpResponse, token, httpLogin);
const httpSetCookie = httpResponse.headers.get("set-cookie") || "";
assert.equal(/secure/i.test(httpSetCookie), false, "HTTP production must not emit Secure");
const httpsLogin = new NextRequest("https://greeny-life.example/api/auth/login", { method: "POST" });
const httpsResponse = NextResponse.json({ success: true });
setSessionCookie(httpsResponse, token, httpsLogin);
const httpsSetCookie = httpsResponse.headers.get("set-cookie") || "";
assert.equal(/secure/i.test(httpsSetCookie), true, "HTTPS production must emit Secure");
console.log("HTTP_SET_COOKIE_HAS_SECURE=" + /secure/i.test(httpSetCookie));
console.log("HTTPS_SET_COOKIE_HAS_SECURE=" + /secure/i.test(httpsSetCookie));
process.env.NODE_ENV = previousNodeEnv;
console.log("Authentication security: PASS");