"""Fail-closed conditions. Transport success must not override policy failure."""

from __future__ import annotations


class FailClosed(Exception):
    def __init__(self, code: str, detail: str = "") -> None:
        self.code = code
        super().__init__(code if not detail else f"{code}:{detail}")


UNKNOWN_AGENT = "UNKNOWN_AGENT"
AUTH_FAILED = "AUTH_FAILED"
ISSUER_UNTRUSTED = "ISSUER_UNTRUSTED"
CAPABILITY_UNKNOWN = "CAPABILITY_UNKNOWN"
CAPABILITY_NOT_AUTHORIZED = "CAPABILITY_NOT_AUTHORIZED"
SEMANTIC_CONTRACT_UNKNOWN = "SEMANTIC_CONTRACT_UNKNOWN"
SEMANTIC_CONTRACT_MISMATCH = "SEMANTIC_CONTRACT_MISMATCH"
SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
RISK_POLICY_DENIED = "RISK_POLICY_DENIED"
AUTHORITY_REQUIRED = "AUTHORITY_REQUIRED"
TARGET_NOT_ALLOWED = "TARGET_NOT_ALLOWED"
UNIFIED_CONTROL_PLANE_UNAVAILABLE = "UNIFIED_CONTROL_PLANE_UNAVAILABLE"
DIRECT_EXECUTION_PATH_FORBIDDEN = "DIRECT_EXECUTION_PATH_FORBIDDEN"
MCP_BYPASS_FORBIDDEN = "MCP_BYPASS_FORBIDDEN"
PUBLIC_LISTENER_DISABLED = "PUBLIC_LISTENER_DISABLED"
SECRET_LEAK_REJECTED = "SECRET_LEAK_REJECTED"
SEAT_IDENTITY_NOT_PUBLIC_AGENT = "SEAT_IDENTITY_NOT_PUBLIC_AGENT"
AUTH_SCOPE_MISSING = "AUTH_SCOPE_MISSING"
