"""Production and transport flags. Only set from exact evidence."""

from __future__ import annotations

A2A_MODE = "FOUNDATION_ONLY"
A2A_PRODUCTION_ACTIVATED = False
A2A_PUBLIC_LISTENER_ENABLED = False
A2A_EXTERNAL_MUTATION_ALLOWED = False
AP2_IMPLEMENTED = False
AP2_ACTIVATED = False

HTTP_PRIMARY = True
NATS_PRIMARY = False
NATS_REPLACED = False
HTTP_FALLBACK_PRESERVED = True

CANONICAL_BOUNDARIES_APPROVED = False
UNIFIED_CONTROL_PLANE_PROVEN = False
C1_PRODUCTION_ACTIVATION_APPROVED = False
CANONICAL_PROMOTION_AUTHORIZED = False
PRODUCTION_ACTIVATION_AUTHORIZED = False
